package com.data;

import com.domain.wx.ArticleItem;
import com.domain.wx.ArticleItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articleitem
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    int countByExample(ArticleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articleitem
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    int deleteByExample(ArticleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articleitem
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articleitem
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    int insert(ArticleItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articleitem
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    int insertSelective(ArticleItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articleitem
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    List<ArticleItem> selectByExample(ArticleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articleitem
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    ArticleItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articleitem
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    int updateByExampleSelective(@Param("record") ArticleItem record, @Param("example") ArticleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articleitem
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    int updateByExample(@Param("record") ArticleItem record, @Param("example") ArticleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articleitem
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    int updateByPrimaryKeySelective(ArticleItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articleitem
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    int updateByPrimaryKey(ArticleItem record);
}