package com.data;

import com.domain.wx.Articles;
import com.domain.wx.ArticlesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticlesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Sat Mar 11 17:08:16 CST 2017
     */
    int countByExample(ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Sat Mar 11 17:08:16 CST 2017
     */
    int deleteByExample(ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Sat Mar 11 17:08:16 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Sat Mar 11 17:08:16 CST 2017
     */
    int insert(Articles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Sat Mar 11 17:08:16 CST 2017
     */
    int insertSelective(Articles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Sat Mar 11 17:08:16 CST 2017
     */
    List<Articles> selectByExample(ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Sat Mar 11 17:08:16 CST 2017
     */
    Articles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Sat Mar 11 17:08:16 CST 2017
     */
    int updateByExampleSelective(@Param("record") Articles record, @Param("example") ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Sat Mar 11 17:08:16 CST 2017
     */
    int updateByExample(@Param("record") Articles record, @Param("example") ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Sat Mar 11 17:08:16 CST 2017
     */
    int updateByPrimaryKeySelective(Articles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Sat Mar 11 17:08:16 CST 2017
     */
    int updateByPrimaryKey(Articles record);
}