package com.data;

import com.domain.wx.ImageMessage;
import com.domain.wx.ImageMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImageMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagemessage
     *
     * @mbggenerated Sat Nov 26 17:03:25 CST 2016
     */
    int countByExample(ImageMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagemessage
     *
     * @mbggenerated Sat Nov 26 17:03:25 CST 2016
     */
    int deleteByExample(ImageMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagemessage
     *
     * @mbggenerated Sat Nov 26 17:03:25 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagemessage
     *
     * @mbggenerated Sat Nov 26 17:03:25 CST 2016
     */
    int insert(ImageMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagemessage
     *
     * @mbggenerated Sat Nov 26 17:03:25 CST 2016
     */
    int insertSelective(ImageMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagemessage
     *
     * @mbggenerated Sat Nov 26 17:03:25 CST 2016
     */
    List<ImageMessage> selectByExample(ImageMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagemessage
     *
     * @mbggenerated Sat Nov 26 17:03:25 CST 2016
     */
    ImageMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagemessage
     *
     * @mbggenerated Sat Nov 26 17:03:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") ImageMessage record, @Param("example") ImageMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagemessage
     *
     * @mbggenerated Sat Nov 26 17:03:25 CST 2016
     */
    int updateByExample(@Param("record") ImageMessage record, @Param("example") ImageMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagemessage
     *
     * @mbggenerated Sat Nov 26 17:03:25 CST 2016
     */
    int updateByPrimaryKeySelective(ImageMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagemessage
     *
     * @mbggenerated Sat Nov 26 17:03:25 CST 2016
     */
    int updateByPrimaryKey(ImageMessage record);
}