package com.data;

import com.domain.wx.MessageRecord;
import com.domain.wx.MessageRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagerecord
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    int countByExample(MessageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagerecord
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    int deleteByExample(MessageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagerecord
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagerecord
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    int insert(MessageRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagerecord
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    int insertSelective(MessageRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagerecord
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    List<MessageRecord> selectByExample(MessageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagerecord
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    MessageRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagerecord
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    int updateByExampleSelective(@Param("record") MessageRecord record, @Param("example") MessageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagerecord
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    int updateByExample(@Param("record") MessageRecord record, @Param("example") MessageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagerecord
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    int updateByPrimaryKeySelective(MessageRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagerecord
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    int updateByPrimaryKey(MessageRecord record);
}