package com.data;

import com.domain.wx.QrCode;
import com.domain.wx.QrCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    int countByExample(QrCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    int deleteByExample(QrCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    int insert(QrCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    int insertSelective(QrCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    List<QrCode> selectByExample(QrCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    QrCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") QrCode record, @Param("example") QrCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    int updateByExample(@Param("record") QrCode record, @Param("example") QrCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    int updateByPrimaryKeySelective(QrCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    int updateByPrimaryKey(QrCode record);
}