package com.data;

import com.domain.wx.WxMedia;
import com.domain.wx.WxMediaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxMediaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxmedia
     *
     * @mbggenerated Sat Mar 11 17:23:54 CST 2017
     */
    int countByExample(WxMediaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxmedia
     *
     * @mbggenerated Sat Mar 11 17:23:54 CST 2017
     */
    int deleteByExample(WxMediaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxmedia
     *
     * @mbggenerated Sat Mar 11 17:23:54 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxmedia
     *
     * @mbggenerated Sat Mar 11 17:23:54 CST 2017
     */
    int insert(WxMedia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxmedia
     *
     * @mbggenerated Sat Mar 11 17:23:54 CST 2017
     */
    int insertSelective(WxMedia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxmedia
     *
     * @mbggenerated Sat Mar 11 17:23:54 CST 2017
     */
    List<WxMedia> selectByExample(WxMediaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxmedia
     *
     * @mbggenerated Sat Mar 11 17:23:54 CST 2017
     */
    WxMedia selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxmedia
     *
     * @mbggenerated Sat Mar 11 17:23:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") WxMedia record, @Param("example") WxMediaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxmedia
     *
     * @mbggenerated Sat Mar 11 17:23:54 CST 2017
     */
    int updateByExample(@Param("record") WxMedia record, @Param("example") WxMediaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxmedia
     *
     * @mbggenerated Sat Mar 11 17:23:54 CST 2017
     */
    int updateByPrimaryKeySelective(WxMedia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxmedia
     *
     * @mbggenerated Sat Mar 11 17:23:54 CST 2017
     */
    int updateByPrimaryKey(WxMedia record);
}