package com.data;

import com.domain.wx.WxTag;
import com.domain.wx.WxTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxtag
     *
     * @mbggenerated Wed Nov 30 21:51:17 CST 2016
     */
    int countByExample(WxTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxtag
     *
     * @mbggenerated Wed Nov 30 21:51:17 CST 2016
     */
    int deleteByExample(WxTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxtag
     *
     * @mbggenerated Wed Nov 30 21:51:17 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxtag
     *
     * @mbggenerated Wed Nov 30 21:51:17 CST 2016
     */
    int insert(WxTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxtag
     *
     * @mbggenerated Wed Nov 30 21:51:17 CST 2016
     */
    int insertSelective(WxTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxtag
     *
     * @mbggenerated Wed Nov 30 21:51:17 CST 2016
     */
    List<WxTag> selectByExample(WxTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxtag
     *
     * @mbggenerated Wed Nov 30 21:51:17 CST 2016
     */
    WxTag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxtag
     *
     * @mbggenerated Wed Nov 30 21:51:17 CST 2016
     */
    int updateByExampleSelective(@Param("record") WxTag record, @Param("example") WxTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxtag
     *
     * @mbggenerated Wed Nov 30 21:51:17 CST 2016
     */
    int updateByExample(@Param("record") WxTag record, @Param("example") WxTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxtag
     *
     * @mbggenerated Wed Nov 30 21:51:17 CST 2016
     */
    int updateByPrimaryKeySelective(WxTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxtag
     *
     * @mbggenerated Wed Nov 30 21:51:17 CST 2016
     */
    int updateByPrimaryKey(WxTag record);
}