package com.domain.wx;

import java.util.Date;

public class AccessToken {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesstoken.id
     *
     * @mbggenerated Sat Mar 11 17:23:30 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesstoken.accountid
     *
     * @mbggenerated Sat Mar 11 17:23:30 CST 2017
     */
    private Integer accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesstoken.token
     *
     * @mbggenerated Sat Mar 11 17:23:30 CST 2017
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesstoken.createtime
     *
     * @mbggenerated Sat Mar 11 17:23:30 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesstoken.expiredtime
     *
     * @mbggenerated Sat Mar 11 17:23:30 CST 2017
     */
    private Date expiredtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesstoken.id
     *
     * @return the value of accesstoken.id
     *
     * @mbggenerated Sat Mar 11 17:23:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesstoken.id
     *
     * @param id the value for accesstoken.id
     *
     * @mbggenerated Sat Mar 11 17:23:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesstoken.accountid
     *
     * @return the value of accesstoken.accountid
     *
     * @mbggenerated Sat Mar 11 17:23:30 CST 2017
     */
    public Integer getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesstoken.accountid
     *
     * @param accountid the value for accesstoken.accountid
     *
     * @mbggenerated Sat Mar 11 17:23:30 CST 2017
     */
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesstoken.token
     *
     * @return the value of accesstoken.token
     *
     * @mbggenerated Sat Mar 11 17:23:30 CST 2017
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesstoken.token
     *
     * @param token the value for accesstoken.token
     *
     * @mbggenerated Sat Mar 11 17:23:30 CST 2017
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesstoken.createtime
     *
     * @return the value of accesstoken.createtime
     *
     * @mbggenerated Sat Mar 11 17:23:30 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesstoken.createtime
     *
     * @param createtime the value for accesstoken.createtime
     *
     * @mbggenerated Sat Mar 11 17:23:30 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesstoken.expiredtime
     *
     * @return the value of accesstoken.expiredtime
     *
     * @mbggenerated Sat Mar 11 17:23:30 CST 2017
     */
    public Date getExpiredtime() {
        return expiredtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesstoken.expiredtime
     *
     * @param expiredtime the value for accesstoken.expiredtime
     *
     * @mbggenerated Sat Mar 11 17:23:30 CST 2017
     */
    public void setExpiredtime(Date expiredtime) {
        this.expiredtime = expiredtime;
    }
}