package com.domain.wx;

public class ArticleItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleitem.id
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleitem.thumb_media_id
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    private String thumbMediaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleitem.author
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleitem.title
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleitem.content_source_url
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    private String contentSourceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleitem.content
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleitem.digest
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    private String digest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleitem.show_cover_pic
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    private Boolean showCoverPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleitem.articlesid
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    private Integer articlesid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleitem.id
     *
     * @return the value of articleitem.id
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleitem.id
     *
     * @param id the value for articleitem.id
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleitem.thumb_media_id
     *
     * @return the value of articleitem.thumb_media_id
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    public String getThumbMediaId() {
        return thumbMediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleitem.thumb_media_id
     *
     * @param thumbMediaId the value for articleitem.thumb_media_id
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    public void setThumbMediaId(String thumbMediaId) {
        this.thumbMediaId = thumbMediaId == null ? null : thumbMediaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleitem.author
     *
     * @return the value of articleitem.author
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleitem.author
     *
     * @param author the value for articleitem.author
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleitem.title
     *
     * @return the value of articleitem.title
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleitem.title
     *
     * @param title the value for articleitem.title
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleitem.content_source_url
     *
     * @return the value of articleitem.content_source_url
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    public String getContentSourceUrl() {
        return contentSourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleitem.content_source_url
     *
     * @param contentSourceUrl the value for articleitem.content_source_url
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    public void setContentSourceUrl(String contentSourceUrl) {
        this.contentSourceUrl = contentSourceUrl == null ? null : contentSourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleitem.content
     *
     * @return the value of articleitem.content
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleitem.content
     *
     * @param content the value for articleitem.content
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleitem.digest
     *
     * @return the value of articleitem.digest
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    public String getDigest() {
        return digest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleitem.digest
     *
     * @param digest the value for articleitem.digest
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    public void setDigest(String digest) {
        this.digest = digest == null ? null : digest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleitem.show_cover_pic
     *
     * @return the value of articleitem.show_cover_pic
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    public Boolean getShowCoverPic() {
        return showCoverPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleitem.show_cover_pic
     *
     * @param showCoverPic the value for articleitem.show_cover_pic
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    public void setShowCoverPic(Boolean showCoverPic) {
        this.showCoverPic = showCoverPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleitem.articlesid
     *
     * @return the value of articleitem.articlesid
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    public Integer getArticlesid() {
        return articlesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleitem.articlesid
     *
     * @param articlesid the value for articleitem.articlesid
     *
     * @mbggenerated Sat Nov 26 20:14:17 CST 2016
     */
    public void setArticlesid(Integer articlesid) {
        this.articlesid = articlesid;
    }
}