package com.domain.wx;

import java.util.Date;

public class ImageMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imagemessage.id
     *
     * @mbggenerated Sat Mar 11 17:25:28 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imagemessage.title
     *
     * @mbggenerated Sat Mar 11 17:25:28 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imagemessage.remark
     *
     * @mbggenerated Sat Mar 11 17:25:28 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imagemessage.url
     *
     * @mbggenerated Sat Mar 11 17:25:28 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imagemessage.createtime
     *
     * @mbggenerated Sat Mar 11 17:25:28 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imagemessage.domain
     *
     * @mbggenerated Sat Mar 11 17:25:28 CST 2017
     */
    private Integer domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imagemessage.accountid
     *
     * @mbggenerated Sat Mar 11 17:25:28 CST 2017
     */
    private Integer accountid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imagemessage.id
     *
     * @return the value of imagemessage.id
     *
     * @mbggenerated Sat Mar 11 17:25:28 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imagemessage.id
     *
     * @param id the value for imagemessage.id
     *
     * @mbggenerated Sat Mar 11 17:25:28 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imagemessage.title
     *
     * @return the value of imagemessage.title
     *
     * @mbggenerated Sat Mar 11 17:25:28 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imagemessage.title
     *
     * @param title the value for imagemessage.title
     *
     * @mbggenerated Sat Mar 11 17:25:28 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imagemessage.remark
     *
     * @return the value of imagemessage.remark
     *
     * @mbggenerated Sat Mar 11 17:25:28 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imagemessage.remark
     *
     * @param remark the value for imagemessage.remark
     *
     * @mbggenerated Sat Mar 11 17:25:28 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imagemessage.url
     *
     * @return the value of imagemessage.url
     *
     * @mbggenerated Sat Mar 11 17:25:28 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imagemessage.url
     *
     * @param url the value for imagemessage.url
     *
     * @mbggenerated Sat Mar 11 17:25:28 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imagemessage.createtime
     *
     * @return the value of imagemessage.createtime
     *
     * @mbggenerated Sat Mar 11 17:25:28 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imagemessage.createtime
     *
     * @param createtime the value for imagemessage.createtime
     *
     * @mbggenerated Sat Mar 11 17:25:28 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imagemessage.domain
     *
     * @return the value of imagemessage.domain
     *
     * @mbggenerated Sat Mar 11 17:25:28 CST 2017
     */
    public Integer getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imagemessage.domain
     *
     * @param domain the value for imagemessage.domain
     *
     * @mbggenerated Sat Mar 11 17:25:28 CST 2017
     */
    public void setDomain(Integer domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imagemessage.accountid
     *
     * @return the value of imagemessage.accountid
     *
     * @mbggenerated Sat Mar 11 17:25:28 CST 2017
     */
    public Integer getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imagemessage.accountid
     *
     * @param accountid the value for imagemessage.accountid
     *
     * @mbggenerated Sat Mar 11 17:25:28 CST 2017
     */
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }
}