package com.domain.wx;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.title
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.mediaid
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    private Integer mediaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.createtime
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.send
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    private Boolean send;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.stateid
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    private Byte stateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.tagid
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    private Integer tagid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.remark
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.toall
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    private Boolean toall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.delwx
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    private Boolean delwx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.title
     *
     * @return the value of message.title
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.title
     *
     * @param title the value for message.title
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.mediaid
     *
     * @return the value of message.mediaid
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    public Integer getMediaid() {
        return mediaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.mediaid
     *
     * @param mediaid the value for message.mediaid
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    public void setMediaid(Integer mediaid) {
        this.mediaid = mediaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.createtime
     *
     * @return the value of message.createtime
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.createtime
     *
     * @param createtime the value for message.createtime
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.send
     *
     * @return the value of message.send
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    public Boolean getSend() {
        return send;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.send
     *
     * @param send the value for message.send
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    public void setSend(Boolean send) {
        this.send = send;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.stateid
     *
     * @return the value of message.stateid
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    public Byte getStateid() {
        return stateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.stateid
     *
     * @param stateid the value for message.stateid
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    public void setStateid(Byte stateid) {
        this.stateid = stateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.tagid
     *
     * @return the value of message.tagid
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    public Integer getTagid() {
        return tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.tagid
     *
     * @param tagid the value for message.tagid
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    public void setTagid(Integer tagid) {
        this.tagid = tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.remark
     *
     * @return the value of message.remark
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.remark
     *
     * @param remark the value for message.remark
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.toall
     *
     * @return the value of message.toall
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    public Boolean getToall() {
        return toall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.toall
     *
     * @param toall the value for message.toall
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    public void setToall(Boolean toall) {
        this.toall = toall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.delwx
     *
     * @return the value of message.delwx
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    public Boolean getDelwx() {
        return delwx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.delwx
     *
     * @param delwx the value for message.delwx
     *
     * @mbggenerated Fri Dec 02 21:02:40 CST 2016
     */
    public void setDelwx(Boolean delwx) {
        this.delwx = delwx;
    }
}