package com.domain.wx;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.title
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.mediaid
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    private String mediaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.createtime
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.stateid
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    private Byte stateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.remark
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.delwx
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    private Boolean delwx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.accountid
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    private Integer accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.domain
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    private Integer domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.type
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    private Short type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.title
     *
     * @return the value of message.title
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.title
     *
     * @param title the value for message.title
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.mediaid
     *
     * @return the value of message.mediaid
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    public String getMediaid() {
        return mediaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.mediaid
     *
     * @param mediaid the value for message.mediaid
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    public void setMediaid(String mediaid) {
        this.mediaid = mediaid == null ? null : mediaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.createtime
     *
     * @return the value of message.createtime
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.createtime
     *
     * @param createtime the value for message.createtime
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.stateid
     *
     * @return the value of message.stateid
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    public Byte getStateid() {
        return stateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.stateid
     *
     * @param stateid the value for message.stateid
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    public void setStateid(Byte stateid) {
        this.stateid = stateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.remark
     *
     * @return the value of message.remark
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.remark
     *
     * @param remark the value for message.remark
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.delwx
     *
     * @return the value of message.delwx
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    public Boolean getDelwx() {
        return delwx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.delwx
     *
     * @param delwx the value for message.delwx
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    public void setDelwx(Boolean delwx) {
        this.delwx = delwx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.accountid
     *
     * @return the value of message.accountid
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    public Integer getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.accountid
     *
     * @param accountid the value for message.accountid
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.domain
     *
     * @return the value of message.domain
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    public Integer getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.domain
     *
     * @param domain the value for message.domain
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    public void setDomain(Integer domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.type
     *
     * @return the value of message.type
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.type
     *
     * @param type the value for message.type
     *
     * @mbggenerated Sat Mar 11 17:24:40 CST 2017
     */
    public void setType(Short type) {
        this.type = type;
    }
}