package com.domain.wx;

import java.util.Date;

public class MessageRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messagerecord.id
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messagerecord.title
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messagerecord.mid
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messagerecord.accountid
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    private Integer accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messagerecord.domain
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    private Integer domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messagerecord.tagid
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    private Integer tagid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messagerecord.openid
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messagerecord.createtime
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messagerecord.remark
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messagerecord.stateid
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    private Byte stateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messagerecord.toall
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    private Boolean toall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messagerecord.msgid
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    private String msgid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messagerecord.id
     *
     * @return the value of messagerecord.id
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messagerecord.id
     *
     * @param id the value for messagerecord.id
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messagerecord.title
     *
     * @return the value of messagerecord.title
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messagerecord.title
     *
     * @param title the value for messagerecord.title
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messagerecord.mid
     *
     * @return the value of messagerecord.mid
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messagerecord.mid
     *
     * @param mid the value for messagerecord.mid
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messagerecord.accountid
     *
     * @return the value of messagerecord.accountid
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public Integer getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messagerecord.accountid
     *
     * @param accountid the value for messagerecord.accountid
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messagerecord.domain
     *
     * @return the value of messagerecord.domain
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public Integer getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messagerecord.domain
     *
     * @param domain the value for messagerecord.domain
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public void setDomain(Integer domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messagerecord.tagid
     *
     * @return the value of messagerecord.tagid
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public Integer getTagid() {
        return tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messagerecord.tagid
     *
     * @param tagid the value for messagerecord.tagid
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public void setTagid(Integer tagid) {
        this.tagid = tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messagerecord.openid
     *
     * @return the value of messagerecord.openid
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messagerecord.openid
     *
     * @param openid the value for messagerecord.openid
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messagerecord.createtime
     *
     * @return the value of messagerecord.createtime
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messagerecord.createtime
     *
     * @param createtime the value for messagerecord.createtime
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messagerecord.remark
     *
     * @return the value of messagerecord.remark
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messagerecord.remark
     *
     * @param remark the value for messagerecord.remark
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messagerecord.stateid
     *
     * @return the value of messagerecord.stateid
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public Byte getStateid() {
        return stateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messagerecord.stateid
     *
     * @param stateid the value for messagerecord.stateid
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public void setStateid(Byte stateid) {
        this.stateid = stateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messagerecord.toall
     *
     * @return the value of messagerecord.toall
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public Boolean getToall() {
        return toall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messagerecord.toall
     *
     * @param toall the value for messagerecord.toall
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public void setToall(Boolean toall) {
        this.toall = toall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messagerecord.msgid
     *
     * @return the value of messagerecord.msgid
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public String getMsgid() {
        return msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messagerecord.msgid
     *
     * @param msgid the value for messagerecord.msgid
     *
     * @mbggenerated Sun Dec 18 14:33:13 CST 2016
     */
    public void setMsgid(String msgid) {
        this.msgid = msgid == null ? null : msgid.trim();
    }
}