package com.domain.wx;

import java.util.Date;

public class QrCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode.id
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode.accountid
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    private Integer accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode.param
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    private String param;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode.remark
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode.createtime
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode.expiredtime
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    private Date expiredtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode.ticket
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    private String ticket;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode.id
     *
     * @return the value of qrcode.id
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode.id
     *
     * @param id the value for qrcode.id
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode.accountid
     *
     * @return the value of qrcode.accountid
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    public Integer getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode.accountid
     *
     * @param accountid the value for qrcode.accountid
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode.param
     *
     * @return the value of qrcode.param
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode.param
     *
     * @param param the value for qrcode.param
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode.remark
     *
     * @return the value of qrcode.remark
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode.remark
     *
     * @param remark the value for qrcode.remark
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode.createtime
     *
     * @return the value of qrcode.createtime
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode.createtime
     *
     * @param createtime the value for qrcode.createtime
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode.expiredtime
     *
     * @return the value of qrcode.expiredtime
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    public Date getExpiredtime() {
        return expiredtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode.expiredtime
     *
     * @param expiredtime the value for qrcode.expiredtime
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    public void setExpiredtime(Date expiredtime) {
        this.expiredtime = expiredtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode.ticket
     *
     * @return the value of qrcode.ticket
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    public String getTicket() {
        return ticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode.ticket
     *
     * @param ticket the value for qrcode.ticket
     *
     * @mbggenerated Sat Mar 11 17:25:50 CST 2017
     */
    public void setTicket(String ticket) {
        this.ticket = ticket == null ? null : ticket.trim();
    }
}