package com.domain.wx;

import java.util.Date;

public class WxMedia {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxmedia.id
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxmedia.title
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxmedia.remark
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxmedia.mediatype
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    private Byte mediatype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxmedia.accountid
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    private Integer accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxmedia.islong
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    private Boolean islong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxmedia.mediaid
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    private String mediaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxmedia.createtime
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxmedia.domain
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    private Integer domain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxmedia.id
     *
     * @return the value of wxmedia.id
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxmedia.id
     *
     * @param id the value for wxmedia.id
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxmedia.title
     *
     * @return the value of wxmedia.title
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxmedia.title
     *
     * @param title the value for wxmedia.title
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxmedia.remark
     *
     * @return the value of wxmedia.remark
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxmedia.remark
     *
     * @param remark the value for wxmedia.remark
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxmedia.mediatype
     *
     * @return the value of wxmedia.mediatype
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    public Byte getMediatype() {
        return mediatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxmedia.mediatype
     *
     * @param mediatype the value for wxmedia.mediatype
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    public void setMediatype(Byte mediatype) {
        this.mediatype = mediatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxmedia.accountid
     *
     * @return the value of wxmedia.accountid
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    public Integer getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxmedia.accountid
     *
     * @param accountid the value for wxmedia.accountid
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxmedia.islong
     *
     * @return the value of wxmedia.islong
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    public Boolean getIslong() {
        return islong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxmedia.islong
     *
     * @param islong the value for wxmedia.islong
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    public void setIslong(Boolean islong) {
        this.islong = islong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxmedia.mediaid
     *
     * @return the value of wxmedia.mediaid
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    public String getMediaid() {
        return mediaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxmedia.mediaid
     *
     * @param mediaid the value for wxmedia.mediaid
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    public void setMediaid(String mediaid) {
        this.mediaid = mediaid == null ? null : mediaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxmedia.createtime
     *
     * @return the value of wxmedia.createtime
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxmedia.createtime
     *
     * @param createtime the value for wxmedia.createtime
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxmedia.domain
     *
     * @return the value of wxmedia.domain
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    public Integer getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxmedia.domain
     *
     * @param domain the value for wxmedia.domain
     *
     * @mbggenerated Sun May 15 20:06:41 CST 2016
     */
    public void setDomain(Integer domain) {
        this.domain = domain;
    }
}