package com.domain.web;

import java.util.Date;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.name
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.url
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.type
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.pid
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.domain
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    private Integer domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.createtime
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.modifytime
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.status
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.ordernum
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    private Integer ordernum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.name
     *
     * @return the value of menu.name
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.name
     *
     * @param name the value for menu.name
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.url
     *
     * @return the value of menu.url
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.url
     *
     * @param url the value for menu.url
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.type
     *
     * @return the value of menu.type
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.type
     *
     * @param type the value for menu.type
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.pid
     *
     * @return the value of menu.pid
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.pid
     *
     * @param pid the value for menu.pid
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.domain
     *
     * @return the value of menu.domain
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    public Integer getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.domain
     *
     * @param domain the value for menu.domain
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    public void setDomain(Integer domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.createtime
     *
     * @return the value of menu.createtime
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.createtime
     *
     * @param createtime the value for menu.createtime
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.modifytime
     *
     * @return the value of menu.modifytime
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.modifytime
     *
     * @param modifytime the value for menu.modifytime
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.status
     *
     * @return the value of menu.status
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.status
     *
     * @param status the value for menu.status
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.ordernum
     *
     * @return the value of menu.ordernum
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    public Integer getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.ordernum
     *
     * @param ordernum the value for menu.ordernum
     *
     * @mbggenerated Wed May 11 14:13:13 CST 2016
     */
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }
}